name: Intelligent Writing Assistance with Text Style Transfer (for GovCloud)
description: >-
  Demonstration of how the NLP task of text style transfer can be applied 
  to enhance the human writing experience.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-07-20"

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.9
    edition: GovCloud

tasks:
  - type: create_job
    name: Install Dependencies
    entity_label: install_dependencies
    script: scripts/install_dependencies.py
    arguments: None
    short_summary: Create job to install dependencies
    long_summary: Create job to install dependencies
    cpu: 2
    memory: 12
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_dependencies
    short_summary: Run job to install dependencies

  - type: start_application
    short_summary: Starting streamlit application
    name: Intelligent Writing Assistance with Text Style Transfer
    subdomain: tst
    script: scripts/launch_app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    cpu: 2
    memory: 4
